import type { Metadata } from "next";
import "@/styles/globals.css";

import { geistMono, geistSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Mai Thread",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
